version: "3.8"

services:
  hello_service:
    build:
      context: ./backend/helloService
      dockerfile: Dockerfile
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend  # Ensure frontend has a Dockerfile
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - hello_service
      - profile_service
